spring:
  application:
    name: dental-appointment
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    com.sao.dentalappointment: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

---
spring:
  profiles: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

---
spring:
  profiles: mariadb
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mariadb://localhost:4306/dental_appointment
    username: root
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver