spring:
  application:
    name: dental-appointment
  h2:
    console:
      enabled: true
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}